server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway



eureka:
  client:
    service-url:  #将自己注册进Eureka服务列表中
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com #自定义服务信息名称
    prefer-ip-address: true #访问路径显示ip地址
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
zuul:
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
  ignored-services: "*"
  prefix: /atguigu
